BEGIN;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();

  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(100) NOT NULL,

  email VARCHAR(255) NOT NULL UNIQUE,

  password VARCHAR(255) NOT NULL,

  role VARCHAR(20) NOT NULL DEFAULT 'USER',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT users_name_not_empty
    CHECK (CHAR_LENGTH(TRIM(name)) >= 2),

  CONSTRAINT users_email_not_empty
    CHECK (CHAR_LENGTH(TRIM(email)) >= 5),

  CONSTRAINT users_role_valid
    CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(150) NOT NULL,

  description TEXT NOT NULL,

  category VARCHAR(100) NOT NULL,

  price NUMERIC(10, 2) NOT NULL,

  stock INTEGER NOT NULL DEFAULT 0,

  image_url TEXT,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT products_name_not_empty
    CHECK (CHAR_LENGTH(TRIM(name)) >= 2),

  CONSTRAINT products_category_not_empty
    CHECK (CHAR_LENGTH(TRIM(category)) >= 2),

  CONSTRAINT products_price_valid
    CHECK (price >= 0),

  CONSTRAINT products_stock_valid
    CHECK (stock >= 0)
);

CREATE TABLE IF NOT EXISTS public.carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id BIGINT NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

  checked_out_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT carts_user_id_foreign
    FOREIGN KEY (user_id)
    REFERENCES public.users(id)
    ON DELETE CASCADE,

  CONSTRAINT carts_status_valid
    CHECK (status IN ('ACTIVE', 'CHECKED_OUT')),

  CONSTRAINT carts_checkout_date_valid
    CHECK (
      (
        status = 'ACTIVE'
        AND checked_out_at IS NULL
      )
      OR
      (
        status = 'CHECKED_OUT'
        AND checked_out_at IS NOT NULL
      )
    )
);

CREATE TABLE IF NOT EXISTS public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  cart_id BIGINT NOT NULL,

  product_id BIGINT NOT NULL,

  quantity INTEGER NOT NULL DEFAULT 1,

  unit_price NUMERIC(10, 2) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT cart_items_cart_id_foreign
    FOREIGN KEY (cart_id)
    REFERENCES public.carts(id)
    ON DELETE CASCADE,

  CONSTRAINT cart_items_product_id_foreign
    FOREIGN KEY (product_id)
    REFERENCES public.products(id)
    ON DELETE RESTRICT,

  CONSTRAINT cart_items_quantity_valid
    CHECK (quantity > 0),

  CONSTRAINT cart_items_unit_price_valid
    CHECK (unit_price >= 0),

  CONSTRAINT cart_items_cart_product_unique
    UNIQUE (cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id BIGINT NOT NULL,

  cart_id BIGINT NOT NULL UNIQUE,

  total NUMERIC(10, 2) NOT NULL,

  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT orders_user_id_foreign
    FOREIGN KEY (user_id)
    REFERENCES public.users(id)
    ON DELETE RESTRICT,

  CONSTRAINT orders_cart_id_foreign
    FOREIGN KEY (cart_id)
    REFERENCES public.carts(id)
    ON DELETE RESTRICT,

  CONSTRAINT orders_total_valid
    CHECK (total >= 0),

  CONSTRAINT orders_status_valid
    CHECK (status IN ('PENDING', 'PAID', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  order_id BIGINT NOT NULL,

  product_id BIGINT NOT NULL,

  product_name VARCHAR(150) NOT NULL,

  quantity INTEGER NOT NULL,

  unit_price NUMERIC(10, 2) NOT NULL,

  subtotal NUMERIC(10, 2) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT order_items_order_id_foreign
    FOREIGN KEY (order_id)
    REFERENCES public.orders(id)
    ON DELETE CASCADE,

  CONSTRAINT order_items_product_id_foreign
    FOREIGN KEY (product_id)
    REFERENCES public.products(id)
    ON DELETE RESTRICT,

  CONSTRAINT order_items_quantity_valid
    CHECK (quantity > 0),

  CONSTRAINT order_items_unit_price_valid
    CHECK (unit_price >= 0),

  CONSTRAINT order_items_subtotal_valid
    CHECK (subtotal >= 0)
);

CREATE INDEX IF NOT EXISTS products_category_index
ON public.products(category);

CREATE INDEX IF NOT EXISTS products_is_active_index
ON public.products(is_active);

CREATE INDEX IF NOT EXISTS carts_user_id_index
ON public.carts(user_id);

CREATE UNIQUE INDEX IF NOT EXISTS carts_one_active_per_user
ON public.carts(user_id)
WHERE status = 'ACTIVE';


CREATE INDEX IF NOT EXISTS cart_items_cart_id_index
ON public.cart_items(cart_id);


CREATE INDEX IF NOT EXISTS cart_items_product_id_index
ON public.cart_items(product_id);


CREATE INDEX IF NOT EXISTS orders_user_id_index
ON public.orders(user_id);


CREATE INDEX IF NOT EXISTS orders_status_index
ON public.orders(status);


CREATE INDEX IF NOT EXISTS order_items_order_id_index
ON public.order_items(order_id);


CREATE INDEX IF NOT EXISTS order_items_product_id_index
ON public.order_items(product_id);

DROP TRIGGER IF EXISTS set_users_updated_at
ON public.users;

CREATE TRIGGER set_users_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


DROP TRIGGER IF EXISTS set_products_updated_at
ON public.products;

CREATE TRIGGER set_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


DROP TRIGGER IF EXISTS set_carts_updated_at
ON public.carts;

CREATE TRIGGER set_carts_updated_at
BEFORE UPDATE ON public.carts
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


DROP TRIGGER IF EXISTS set_cart_items_updated_at
ON public.cart_items;

CREATE TRIGGER set_cart_items_updated_at
BEFORE UPDATE ON public.cart_items
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();


DROP TRIGGER IF EXISTS set_orders_updated_at
ON public.orders;

CREATE TRIGGER set_orders_updated_at
BEFORE UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.users
FROM anon, authenticated;

REVOKE ALL ON TABLE public.products
FROM anon, authenticated;

REVOKE ALL ON TABLE public.carts
FROM anon, authenticated;

REVOKE ALL ON TABLE public.cart_items
FROM anon, authenticated;

REVOKE ALL ON TABLE public.orders
FROM anon, authenticated;

REVOKE ALL ON TABLE public.order_items
FROM anon, authenticated;

GRANT ALL ON TABLE public.users
TO service_role;

GRANT ALL ON TABLE public.products
TO service_role;

GRANT ALL ON TABLE public.carts
TO service_role;

GRANT ALL ON TABLE public.cart_items
TO service_role;

GRANT ALL ON TABLE public.orders
TO service_role;

GRANT ALL ON TABLE public.order_items
TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES
IN SCHEMA public
TO service_role;


COMMIT;